version: "3.1"

services:
    mailpit:
        image: "axllent/mailpit:latest"
        ports:
            - "${FORWARD_MAILPIT_PORT:-1025}:1025"
            - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
        restart: always
        networks:
            - laravel

    meilisearch:
        image: "getmeili/meilisearch:latest"
        ports:
            - "${FORWARD_MEILISEARCH_PORT:-7700}:7700"
        environment:
            MEILI_NO_ANALYTICS: "${MEILISEARCH_NO_ANALYTICS:-false}"
        volumes:
            - "laravel-meilisearch:/meili_data"
        restart: always
        networks:
            - laravel
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--spider",
                    "http://localhost:7700/health",
                ]
            retries: 3
            timeout: 5s

    minio:
        image: "minio/minio:latest"
        ports:
            - "${FORWARD_MINIO_PORT:-9000}:9000"
            - "${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900"
        environment:
            MINIO_ROOT_USER: "laravel"
            MINIO_ROOT_PASSWORD: "password"
        restart: always
        volumes:
            - "laravel-minio:/data/minio"
        networks:
            - laravel
        command: minio server /data/minio --console-address ":8900"
        healthcheck:
            test:
                ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            retries: 3
            timeout: 5s

    soketi:
        image: "quay.io/soketi/soketi:latest-16-alpine"
        environment:
            SOKETI_DEBUG: "${SOKETI_DEBUG:-1}"
            SOKETI_METRICS_SERVER_PORT: "9601"
            SOKETI_DEFAULT_APP_ID: "${PUSHER_APP_ID}"
            SOKETI_DEFAULT_APP_KEY: "${PUSHER_APP_KEY}"
            SOKETI_DEFAULT_APP_SECRET: "${PUSHER_APP_SECRET}"
        ports:
            - "${PUSHER_PORT:-6001}:6001"
            - "${PUSHER_METRICS_PORT:-9601}:9601"
        restart: always
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
volumes:
    laravel-meilisearch:
        driver: local
    laravel-minio:
        driver: local
